Feat: driving stats
Hyundai-Kia-Connect/hyundai_kia_connect_api pull request #139
Opened 2022-11-22 10:40 UTC by zulufoxtrot

Driving stats, Continued work from https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/107

It works but I'm not sure about the implementation.
I kind of hacked the current implem: used a dataclass to store a day, then put that object into the dict returned by _get_driving_info. Not very clean but I don't see how to do it better without refactoring the whole thing.

I also don't know if/how it works with other regions. Tested on Kia EU only.

Feel free to suggest changes.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1007033/203291879-7b28642e-cda5-40dc-b657-803008aecf7f.png">

2022-11-22 17:46 UTC, cdnninja commented
This is awesome work!  Really appreciate it.  I added a few comments.

2022-11-22 19:04 UTC, zulufoxtrot commented
Thank you. I can't see your comments, maybe you need to submit your review?

2022-11-22 19:48 UTC, cdnninja requested changes

2022-11-23 15:31 UTC, zulufoxtrot commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        state = self._get_driving_info(token, vehicle)
Got it.
- added a try except block
- removed the try except block from _get_driving_info, it's better to have it IMO.

2022-11-24 16:28 UTC, cdnninja commented on hyundai_kia_connect_api/Vehicle.py
> +    # distance is expressed in (I assume) whatever unit the vehicle is configured in. KMs (rounded) in my case
I am thinking we use a default for now.   Also happy to learn from you on best practices.  This is just a hobby for me you seem to have more best practice experience.

2022-11-24 20:57 UTC, zulufoxtrot commented on hyundai_kia_connect_api/Vehicle.py
> +    # distance is expressed in (I assume) whatever unit the vehicle is configured in. KMs (rounded) in my case
OK! I'll try to update this PR asap.

2022-11-28 10:44 UTC, zulufoxtrot commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        vehicle.total_power_consumed = get_child_value(state, "totalPwrCsp")
It's watt-hours (Wh). The units are not given explicitly by the API on this endpoint.
Contrarily to distances/temperatures, which can depend on the region, I think energy & power values will always be expressed in Wh or kWh.

Based on this assumption, I suggest to:
- not define a unit, and remove the following attributes: `_total_power_consumed_unit`, `_power_consumption_30d_unit`, `_total_power_consumed_value`, `_power_consumption_30d_value`
- document the remaining attributes: `_total_power_consumed`, `_power_consumption_30d`. Add a comment speciflying the unit
- make these 2 attributes public (remove underscore prefix) and remove their getters and setters, for simplification

What do you think?

2022-11-28 15:25 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        vehicle.total_power_consumed = get_child_value(state, "totalPwrCsp")
I'm good with this! If we find another region uses a different unit we can fix at that time.

2022-11-28 15:27 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        vehicle.total_power_consumed = get_child_value(state, "totalPwrCsp")
Let me know when you are ready for me to merge.

2022-11-28 16:46 UTC, zulufoxtrot commented on hyundai_kia_connect_api/Vehicle.py
> +    # distance is expressed in (I assume) whatever unit the vehicle is configured in. KMs (rounded) in my case
distance unit attribute added, set to KM by default

2022-11-28 16:47 UTC, zulufoxtrot commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        vehicle.total_power_consumed = get_child_value(state, "totalPwrCsp")
changes implemented as discussed.

2022-11-28 16:48 UTC, zulufoxtrot commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        vehicle.total_power_consumed = get_child_value(state, "totalPwrCsp")
If you're OK with the result, you can merge.

2022-11-28 18:20 UTC, merged