feat(EU): Charge Port Action
Hyundai-Kia-Connect/hyundai_kia_connect_api pull request #153
Opened 2022-11-30 04:34 UTC by cdnninja

2022-11-30 09:01 UTC, zulufoxtrot requested changes

2022-11-30 09:04 UTC, zulufoxtrot commented
Looking good.

So I see this is a V2 endpoint, do we know which cars are compatible?
I don't think my 2020 niro has the ability to remotely operate the charge port.
How do we handle differences in support for cars?
I'm fine with not performing pre checks and letting the API reject the request.

2022-11-30 09:17 UTC, zulufoxtrot requested changes

2022-11-30 09:17 UTC, zulufoxtrot commented on hyundai_kia_connect_api/ApiImpl.py
> +    def charge_port_action(self, token: Token, vehicle: Vehicle, action: str) -> str:
action: CHARGE_PORT_ACTION

2022-12-02 19:45 UTC, cdnninja commented
> The original request is for Hyundai EU, but this PR implements the feature in Kia EU. Is it intended? [Hyundai-Kia-Connect/kia_uvo#243](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/243)

KIA/Hyundai are the same API in the EU just different endpoints.   Only region that doesn't combine the two is USA.

2022-12-02 19:45 UTC, cdnninja commented
> Looking good.
> 
> So I see this is a V2 endpoint, do we know which cars are compatible? I don't think my 2020 niro has the ability to remotely operate the charge port. How do we handle differences in support for cars? I'm fine with not performing pre checks and letting the API reject the request.

No unfortunately I am not sure which cars support it and which don't.

2022-12-02 20:54 UTC, zulufoxtrot approved these changes

2022-12-02 20:58 UTC, zulufoxtrot commented
> No unfortunately I am not sure which cars support it and which don't.

OK.

Maybe at some point we could implement something to let the user know if the car is compatible with the action. I'm not sure it's a good idea to do it at the library level, though. And it requires maintenance (adding car models as they get released).

Feel free to merge, https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/155 is stalled at the moment.

2022-12-02 21:10 UTC, cdnninja commented
It wouldn't be bad for us to collect it as we know.  I have commented in the kia_uvo side to validate using your native app.  If it exists in that it will probably work.    The native apps must have a way of knowing though.

2022-12-02 21:10 UTC, merged