Updates for India region
Hyundai-Kia-Connect/hyundai_kia_connect_api pull request #499
Opened 2024-02-10 07:38 UTC by gowthamgowtham

Works for India region. I haven't managed to add new tests. I am sure some cleanup will be necessary.

2024-02-10 14:15 UTC, cdnninja commented
Thanks for doing this! I'll run through feedback this weekend.   Are you able to cleanup merge conflicts and potentially rebase?  It shows a lot of changes that may not be real.  It will help with review. 


Version commit also needs to be backed out.  The system does that.

2024-02-10 22:57 UTC, cdnninja requested changes

2024-02-10 22:57 UTC, cdnninja commented on india.py
This should either:

1. Removed.
2. Moved to the test folders and we load your creds into a secret in the repo so these tests are run like EU.   No pressure though.

2024-02-10 22:57 UTC, cdnninja commented on hyundai_kia_connect_api/Vehicle.py
> -    summary: TripInfo = None
Be removing this it will break other regions.   I also think adding the below will break other regions.  Can we conform to existing?

2024-02-10 22:57 UTC, cdnninja commented on hyundai_kia_connect_api/Vehicle.py
> +@dataclass
Location is already handled and used in other values.  No need for a new class.

2024-02-10 22:57 UTC, cdnninja commented on hyundai_kia_connect_api/Vehicle.py
> +import decimal
We use floats.

2024-02-10 22:57 UTC, cdnninja commented on hyundai_kia_connect_api/Vehicle.py
> -    hhmmss: str = None  # will not be filled by summary
Removing fields will break other regions and not work for kia_uvo.   Please try to use the existing fields if possible.

2024-02-10 22:57 UTC, cdnninja commented on hyundai_kia_connect_api/HyundaiApiIN.py
> +        state = self._get_location(token, vehicle)
This needs protective logic.  By doing this in a cached call you will kill the vehicle battery.  Cached calls shouldn't hit the car each call.

2024-02-10 22:58 UTC, cdnninja requested changes

2024-02-10 22:58 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiAU.py
Could you remove these changes just to keep the PR clean?

2024-02-11 00:26 UTC, cdnninja requested changes

2024-02-11 00:26 UTC, cdnninja commented on hyundai_kia_connect_api/HyundaiApiIN.py
> +        _LOGGER.error(f"Disabling force refresh")
Add domain like other logging to clarify what is throwing this.    I assume this exists since force refresh command doesn't work yet?

2024-04-08 07:19 UTC, CodeWithShreyans commented
any updates on this?

2024-07-11 10:27 UTC, nishant713 commented
Hi @gowthamgowtham any update?

2024-07-21 15:28 UTC, ohuc commented
any updates

2024-11-24 16:01 UTC, nishant713 commented
@gowthamgowtham any update?

2025-04-07 13:32 UTC, nishant713 commented
Hi @cdnninja @fuatakgun 
Using @gowthamgowtham 's branch and the india.py I am able to get information from my car using python on my local machine (not HA). 

Is it possible to be of some help remotely so as to resolve the issues and finish Indian bluelink integration?

I'm not much good at programming or gift, but can run python on my machine

2025-04-17 22:05 UTC, cdnninja commented
Is that when you first connect or on an action?

2025-04-17 22:06 UTC, cdnninja commented
If you also create a PR to this repo it will let me comment on specific parts of the code.

2025-04-23 00:15 UTC, closed without merging