EU: Add setting charge limits
Hyundai-Kia-Connect/hyundai_kia_connect_api pull request #53
Opened 2022-03-17 10:54 UTC by jwefers

tested with EU Ioniq Electric

2022-04-15 01:07 UTC, cdnninja requested changes

2022-04-15 01:07 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        return str(response.status_code == 200)
@jwefers  just wanted to check on this.

2022-04-15 01:30 UTC, cdnninja commented
Are you able to resolve the merge conflicts and then we can merge?

2022-04-24 12:14 UTC, jwefers commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        return str(response.status_code == 200)
@cdnninja i think there was no such header, but i'll confirm

2022-04-24 12:18 UTC, jwefers commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        return str(response.status_code == 200)
unfortunately, EU api only returns an Etag and rate-limit state

2022-04-24 12:23 UTC, jwefers commented
failing test is interesting, Fuats car response seems to miss `vehicleStatus.evStatus.reservChargeInfos.targetSOClist` in this instance

2022-09-08 21:08 UTC, CreasolTech commented
@jwefers jwefers, how do you call set_charge_limits() ?
I'm very basic with python, and tried to use vm.set_charge_limits(vehicleId, evchargelimits) but I've found that your implementation in KiaUvoApiEU.py uses 
```set_charge_limits(self, token: Token, vehicle: Vehicle, ac_limit: int, dc_limit: int)```
instead of
```set_charge_limits(self, token: Token, vehicle: Vehicle, limits: EvChargeLimits)```  

Thanks a lot.

2022-09-10 08:08 UTC, jwefers commented
@CreasolTech i refactored the method in an earlier PR which has since been merged, check https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/Vehicle.py now, you can see the `EvChargeLimits`class there

2022-09-10 08:15 UTC, jwefers commented
@fuatakgun So the test suite based on your car does not work for this EU feature - are you okay with merging this as is? Otherwise we could dig into adding Github secrets for my car for a EU test suite - some time in the future.

2022-09-13 10:12 UTC, CreasolTech commented
> 

Are you sure? 
I can't find the set_charge_limit method on the current repository for Kia Europe.
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/KiaUvoApiEU.py

2022-11-02 17:29 UTC, merged