Fix #514 Genesis EU authentication (needs review)
Hyundai-Kia-Connect/hyundai_kia_connect_api pull request #638
Opened 2024-09-27 08:33 UTC by RobXYZ

This is a fix for #514 

I initially tried to adjust the existing auth flow but couldn’t get it to work so started from scratch. I recorded the API and reproduced the HTTP requests in a test script then incorporated it. I am not sure if all steps are required.

Apologies if the code is messy, I don’t fully understand the API or library and used ChatGPT to mash it all together. This code works for Genesis but may have broken the other brands. Hopefully it’s a start and someone with better knowledge and skills can take a look through and tidy it up or suggest changes before merging.

2024-10-04 18:59 UTC, cdnninja commented
This does break other brands as you can see from the failed test build, that calls a real car.  

This code will need to be aligned to existing if close enough logic, which it appears to be.  If drastically different a new class needs to be defined.

2025-03-06 23:24 UTC, cdnninja commented
Someone with a Genesis will need to complete the required changes before it is merged.  Currently this code breaks the other brands.

2025-03-07 09:27 UTC, RobXYZ commented
I will try to integrate the code properly

2025-03-07 13:29 UTC, RobXYZ commented
I tried to update the existing authentication flow but it always failed to fetch the token. Even comparing HTTP requests I couldn’t figure out why. Instead I’ve created a new flow for Genesis replicating exactly what I logged from my phone app and this seems to work for me.

2025-03-10 11:45 UTC, RobXYZ commented
Yes, I've been using it in Home Assistant since September and everything seems to work with with our electrified GV70 once the authentication is successful.

You can test it by manually installing the Kia Uvo integration in Home Assistant (place in custom_components) and change the requirements line in manifest.json to:

`"requirements": ["git+https://github.com/RobXYZ/hyundai_kia_connect_api.git@master#egg=hyundai_kia_connect_api"],`

2025-03-12 17:54 UTC, RobXYZ commented
The test script I initially used to replicate the app might be an easier starting point for that:

```
import requests
import re

# Define variables for login
USERNAME = ""
PASSWORD = ""
SERVICE_ID = "3020afa2-30ff-412a-aa51-d28fbe901e10"
USER_AGENT = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148_CCS_APP_iOS"

# Initialize a session to handle cookies and persist settings
session = requests.Session()
session.headers.update({
    "User-Agent": USER_AGENT,
    "Accept-Language": "en-GB,en;q=0.9",
})
# Disable SSL verification for testing via a reverse proxy
session.verify = False

def debug_response(response):
    """Print debugging information for the given response object."""
    print(f"URL: {response.url}")
    print(f"Status Code: {response.status_code}")
    print("Headers:")
    for key, value in response.headers.items():
        print(f"  {key}: {value}")
    print("\nCookies stored in session:", session.cookies.get_dict())
    if response.text:
        print("\nResponse Content (truncated):")
        print(response.text[:500])  # Truncate to first 500 characters for readability
    print("=" * 80 + "\n")

def get_initial_cookie():
    # Step 1: GET oauth2 - sets initial cookie
    url = f"https://prd-eu-ccapi.genesis.com/api/v1/user/oauth2/authorize?response_type=code&client_id={SERVICE_ID}&redirect_uri=https://accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2&lang=en&scope=url.newapp"
    response = session.get(url, allow_redirects=False)
    debug_response(response)

    if response.status_code == 302:
        session.cookies.update(response.cookies)
        return response.headers["Location"]
    raise Exception("Initial OAuth2 request failed")

def fetch_authorize_page(location_url):
    # Step 2: Follow the 302 to fetch authorize page
    response = session.get(location_url)
    debug_response(response)
    return response.status_code == 200

def get_session():
    # Step 3: GET session
    url = "https://prd-eu-ccapi.genesis.com/api/v1/user/session"
    response = session.get(url)
    debug_response(response)
    return response.status_code == 204

def set_language():
    # Step 4: POST language
    url = "https://prd-eu-ccapi.genesis.com/api/v1/user/language"
    headers = {"Content-Type": "text/plain;charset=UTF-8"}
    response = session.post(url, headers=headers, json={"lang": "en"})
    debug_response(response)
    return response.status_code == 204

def get_integration_info():
    # Step 5: GET integration info
    url = "https://prd-eu-ccapi.genesis.com/api/v1/user/integrationinfo"
    response = session.get(url)
    debug_response(response)

    if response.status_code == 200:
        return response.json()
    raise Exception("Failed to get integration info")

def perform_login(integration_info):
    # Step 6: Retrieve login form URL
    url = f"https://accounts-eu.genesis.com/realms/eugenesisidm/protocol/openid-connect/auth?client_id=ga-gcs&scope=openid%20profile%20email%20phone&response_type=code&redirect_uri=https://prd-eu-ccapi.genesis.com/api/v1/user/integration/redirect/login&ui_locales=en&state={integration_info['serviceId']}:{integration_info['userId']}"
    response = session.get(url)
    debug_response(response)
    
    # Extract "loginAction" URL from the response
    match = re.search(r'"loginAction":\s*"(https://.*?)"', response.text)
    if not match:
        raise Exception("Could not find loginAction URL")
    
    login_action_url = match.group(1)

    # Step 7: Submit username and password to login
    payload = {
        "username": USERNAME,
        "password": PASSWORD
    }
    response = session.post(login_action_url, data=payload, allow_redirects=False)
    debug_response(response)
    
    if response.status_code == 302:
        session.cookies.update(response.cookies)
        return response.headers["Location"]
    raise Exception("Login failed")

def follow_redirects(redirect_url):
    # Step 8: Follow the 302 redirects until the final step
    response = session.get(redirect_url, allow_redirects=True)
    debug_response(response)
    if response.status_code == 200:
        return True
    raise Exception("Redirect failed")

def perform_silent_signin():
    # Step 9: Perform silent signin to obtain the code
    url = "https://prd-eu-ccapi.genesis.com/api/v1/user/silentsignin"
    headers = {"Content-Type": "text/plain;charset=UTF-8"}
    response = session.post(url, headers=headers, json={"intUserId": ""})
    debug_response(response)

    if response.status_code == 200:
        return response.json().get("redirectUrl")
    raise Exception("Silent signin failed")

def get_access_token(redirect_url):
    # Step 10: Fetch the access token using the authorization code
    session_code = re.search(r'code=([^&]*)', redirect_url).group(1)
    
    url = "https://prd-eu-ccapi.genesis.com/api/v1/user/oauth2/token"
    payload = {
        "client_id": SERVICE_ID,
        "code": session_code,
        "grant_type": "authorization_code",
        "redirect_uri": "https://accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2"
    }
    headers = {
        "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
        "Authorization": "Basic MzAyMGFmYTItMzBmZi00MTJhLWFhNTEtZDI4ZmJlOTAxZTEwOkZLRGRsZWYyZmZkbGVGRXdlRUxGS0VSaUxFUjJGRUQyMXNEZHdkZ1F6NmhGRVNFMw=="
    }
    
    response = session.post(url, headers=headers, data=payload)
    debug_response(response)

    if response.status_code == 200:
        return response.json().get("access_token")
    raise Exception("Failed to get access token")

# Execute the flow with debugging
try:
    redirect_location = get_initial_cookie()
    fetch_authorize_page(redirect_location)
    get_session()
    set_language()
    integration_info = get_integration_info()
    redirect_url = perform_login(integration_info)
    follow_redirects(redirect_url)
    redirect_url_with_code = perform_silent_signin()
    access_token = get_access_token(redirect_url_with_code)

    print(f"Access Token: {access_token}")
except Exception as e:
    print(f"An error occurred: {e}")

```

2025-03-13 00:00 UTC, cdnninja commented
This code for sure can be used and tested without home assistant.  That's why it is a separate library.   Other services consume this too.

2025-03-14 01:14 UTC, cdnninja requested changes
My impression is this code is near identical to our current flows with a few changes.   Could you see if you can reduce the duplicate code?

2025-03-14 01:14 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +            raise AuthenticationError("Failed to set language")
This looks to be duplicate of _set_session_language so that should be used for supportability.

2025-03-14 01:14 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +        # Step 5: Get integration info
Below this looks to be the same as _get_authorization_code_with_form?

2025-03-14 01:14 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +                "client_id": self.CCSP_SERVICE_ID,
For this flow is this the only key difference? If so I would think can reuse code with less duplication.

2025-03-14 01:14 UTC, cdnninja commented on hyundai_kia_connect_api/KiaUvoApiEU.py
> +USER_AGENT_GENESIS: str = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148_CCS_APP_iOS"  # noqa
Have you tried using the same user agent of USER_AGENT_MOZILLA?   I would think both will work.  Less code to take care of.

2025-06-19 09:49 UTC, martinpelant commented
I've been using this successfully for few months now for my GV60 in the UK. Any chance in merging it into mainline?

2025-06-19 12:57 UTC, cdnninja commented
It has merge conflicts and open feedback.

2025-06-19 13:40 UTC, RobXYZ commented
I've tried adapting the existing code a few times without success. I can't work out why it's failing but I eventually get blacklisted by the Genesis servers. I am hoping a fresh pair of eyes can figure out the exact changes - it might be something very obvious I am not seeing

2025-06-19 20:29 UTC, pasqualito79 commented
@cdnninja there are a few guys really be glad to get Genesis support out of this code, also in other projects which use it. I can only help testing, not developing or solving conflicts, but I just want to speak for those few people who would be happy to get support for their car in different kind of applications. So if I could help with testing, just let me know and maybe you have some time telling @RobXYZ what needs to be done to finally get this into main branch. thanks!

2025-06-20 21:29 UTC, cdnninja commented
First step would be resolving the merge conflicts.  After that I could propose specific sections to re-use.  Key is retesting after each consolidation.

2025-07-14 20:11 UTC, martinpelant commented
rebased on top of master and incorporated latest expires_in in https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/84716a812b3a3bc0898f970974bd91184575dfaa 

Testing locally for now

2025-07-17 22:15 UTC, martinpelant commented
no issues so far

2025-07-20 20:27 UTC, pasqualito79 commented
but still there seem some conflicts :-(

2025-07-20 20:45 UTC, cdnninja commented
> rebased on top of master and incorporated latest expires_in in https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/84716a812b3a3bc0898f970974bd91184575dfaa 
> 
> 
> 
> Testing locally for now 

Feel free to create a pull request if you have code that's rebased.   It will also need to shrink the duplicate code.

2025-07-20 20:48 UTC, martinpelant commented
there is another API change in seatHeaterVentState  which I locally commented out to unbreak myself today: https://github.com/martinpelant/hyundai_kia_connect_api_genesis/commit/3f67c9eb0ab50c6c2185d0a536a47028ce27e944

2025-08-02 18:39 UTC, cdnninja commented
FYI lots just changed in the EU authentication flow.  It would be worth sniffing the Genesis flow to see if it aligns with hyundai/Kias' new flow. If so all you will need is a few URLs and the client ID.

2025-08-02 22:05 UTC, pasqualito79 commented
Hello @cdnninja - here's the message flow with the newest iOS app which was released this week. I replaced all tokens, ID's. This is the flow for a new login from scratch, after that selecting the vehicle and doing a status refresh.

```
GET https://prd-eu-ccapi.genesis.com/api/v1/user/integration/redirect/login?state=<ID>&session_state=<ID>

GET https://prd-eu-ccapi.genesis.com/web/v1/user/integration/auth?&locale=de&country=ch

POST https://prd-eu-ccapi.genesis.com/api/v1/user/language

POST https://prd-eu-ccapi.genesis.com/api/v1/user/silentsignin

POST https://prd-eu-ccapi.genesis.com/api/v1/user/oauth2/token

POST https://prd-eu-ccapi.genesis.com/api/v2/apps/dkc2/dkcsa/dkcdkss/api/v1/registerDigitalKeyDeviceInfo

POST https://prd-eu-ccapi.genesis.com/api/v1/spa/notifications/<ID>/register

GET https://prd-eu-ccapi.genesis.com/api/v1/user/profile

POST https://prd-eu-ccapi.genesis.com/api/v1/spa/devices/<ID>/setting/language

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>profile

GET https://prd-eu-ccapi.genesis.com/api/v1/profile/updateinfo?car_id=<ID>=1&lang=de

POST https://prd-eu-ccapi.genesis.com/api/v1/spa/notifications/<ID>/register

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/profile

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>setting/service

POST https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/control/engine

GET https://egw-svchub-ccs-g-eu.eu-central.hmgmobility.com:31010/api/v3/servicehub/device/host

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/notifications/<ID>/count/new

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/notifications/<ID>/count/new

POST https://egw-svchub-ccs-g-eu.eu-central.hmgmobility.com:31010/api/v3/servicehub/device/register

GET https://egw-svchub-ccs-g-eu.eu-central.hmgmobility.com:31010/api/v3/servicehub/vehicles/metadatalist?brand=G&carId=<ID>

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>setting/service

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/status/valet

GET https://prd-eu-ccapi.genesis.com/api/v1/profile/users/<ID>/cars/<ID>

POST https://egw-svchub-ccs-g-eu.eu-central.hmgmobility.com:31010/api/v3/servicehub/device/protocol

POST https://prd-eu-ccapi.genesis.com/api/v1/spa/services/weather

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/ccs2/carstatus/latest

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/location/park

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/finaldestination

GET https://egw-svchub-ccs-g-eu.eu-central.hmgmobility.com:31010/api/v3/vstatus/connstate?clientId=<ID>

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/ccs2/carstatus/latest

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/notifications/<ID>/count/new

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/e<ID>/ccs2/carstatus/latest

PUT https://prd-eu-ccapi.genesis.com/api/v1/user/pin

GET https://prd-eu-ccapi.genesis.com/api/v2/spa/vehicles/<ID>/ccs2/carstatus

GET https://prd-eu-ccapi.genesis.com/api/v1/spa/vehicles/<ID>/ccs2/carstatus/latest
```

2025-09-04 22:10 UTC, martinpelant commented
rebased to latest master. Tested both genesis & kia working: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/40e6682ef5a0d59b67dbe623c0ba6329db4d8a9b

2025-09-04 23:21 UTC, cdnninja commented
Could you create a fresh pull request?

2025-09-05 19:17 UTC, martinpelant commented
done: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/879

2025-09-06 16:51 UTC, AndreasLat commented
Das tönt ja spannend, bei mir kommt aber für den GV70 electrified immer noch eine Fehlermeldung und die Einbindung klappt nicht.

2025-10-08 18:49 UTC, lmuser22 commented
> Das tönt ja spannend, bei mir kommt aber für den GV70 electrified immer noch eine Fehlermeldung und die Einbindung klappt nicht.

Hast Du schon ein Weg gefunden? Nach gut 3 Jahren würde ich gerne mit GV60 auch einbinden :)

2025-10-22 12:06 UTC, RustyDust commented
@pasqualito79 

> here's the message flow with the newest iOS app which was released this week. I replaced all tokens, ID's. 

Given your experience with the Geneses login flow, do you think you could patch [this](https://gist.github.com/RustyDust/e2a7be978affd85fb5ef5a345f31f67a) to support Genesis as well?

2025-10-22 12:13 UTC, martinpelant commented
I tried to get the refresh token. With following URL I'm able to grab the long code which will show up in this inaccessible url after logging in: `https://oneapp.genesis.com/redirect?code=<the long code>&state=hmgoneapp&login_success=y`

https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/authorize?client_id=50e3b8b0-ced5-43b7-8a42-f86ac92fe50e&scope=account.token.transfer%20account.id.generate%20account.puid.userinfos%20account.userinfo%20read%20account.userinfos%20puid%20email%20name%20mobileNum%20birthdate%20lang%20country%20signUpDate%20gender%20nationInfo%20certProfile%20offline&response_type=code&redirect_uri=https://oneapp.genesis.com/redirect&state=hmgoneapp&ui_locales=en-GB


However I haven't figured out the correct redirect URL where we pass this long code to get the actual refresh token. If anyone has some time to dig into it hat would be great.

2025-10-22 12:20 UTC, martinpelant commented
this is what I get 
```
❌ Error getting tokens from der API!
{"retId":"47ff3fb4-14e7-407b-896b-b408c0a5fbbe","retCode":7405,"retMsg":"Invalid redirect uri","retSubMsg":"\"invalid request. mapping info or inputModel is null. can not validate redirect uri.\"","retValue":null}
Cleaning up and closing the browse
```
if I post 
```
data = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": "https://prd-eu-ccapi.genesis.com/api/v1/user/oauth2/token",
            "client_id":"50e3b8b0-ced5-43b7-8a42-f86ac92fe50,
            "client_secret":"KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV,
        }
```

to `https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/token`

(also not sure where to get client secret)

2025-10-22 12:29 UTC, RustyDust commented
> (also not sure where to get client secret)

I was hoping that @pasqualito79 could share some insights on that for the `client_secret` seems to be the only part still missing. That said, from looking at the solutions for Hyundai/Kia, the `redirect_uri` should probably be `https://prd-eu-ccapi.genesis.com:8080/api/v1/user/oauth2/token`.

2025-10-22 12:34 UTC, martinpelant commented
Tried that, still same error. Also tried `https://stg.eu-ccapi.genesis.com:8081/api/v1/user/oauth2/token` which I found in decompiled my genesis app: 
https://gist.github.com/martinpelant/e38a6c32251f7e495baf998f3eb61fe3#file-gistfile1-txt-L143 
no difference in error message

2025-10-22 12:36 UTC, pasqualito79 commented
I would love to help, but I'm not a developer. So if you need anything which I can achieve by testing or any data that's visible when using proxyman I'll try...

2025-10-22 12:37 UTC, martinpelant commented
this is what I've been using to try those url: https://gist.github.com/martinpelant/dddafa6304706b8efcafaf14561eeea6

2025-10-22 12:39 UTC, RustyDust commented
@pasqualito79 
> I would love to help, but I'm not a developer. So if you need anything which I can achieve by testing or any data that's visible when using proxyman I'll try...

Well, if you could look through your trace and check whether there's something in there that looks like the client_secret, that would be helpful. Should be in the same request as the `client_id` which seems to be "50e3b8b0-ced5-43b7-8a42-f86ac92fe50".

2025-10-22 12:42 UTC, martinpelant commented
Client ID might be differen on iOS? (mine I was able to grab from Android but couldn't get through login flow as my genesis app has root detectors which closes the app after few seconds (and I need root to bypass ssl and grab the url)

2025-10-22 12:48 UTC, RustyDust commented
The client id may be different on iOS but for grabbing the refresh token it shouln't matter what is used as long as the combination of client_id and client_secret matches.

2025-10-22 12:50 UTC, pasqualito79 commented
Ok, I should be able to provide this, but aren't those values user-specific?

2025-10-22 12:59 UTC, pasqualito79 commented
It seems that the new Genesis app blocks the proxyman VPN now but I still have saved some old requests from August. There I have: clientId: c3c4421b-9d8b-cc9a-5271-181af6a1b0db

2025-10-22 13:07 UTC, RustyDust commented
> Ok, I should be able to provide this, but aren't those values user-specific?

No, they are app-specific. So for example the Android app has its own combination of client_id and client_secret but these are the same for every user of the app. The user specific parts are username and password and then of course the generated refresh token.

2025-10-22 13:08 UTC, RustyDust commented
> It seems that the new Genesis app blocks the proxyman VPN now but I still have saved some old requests from August. There I have: clientId: c3c4421b-9d8b-cc9a-5271-181af6a1b0db

Doesn't help much without the client_secret, unfortunately.

2025-10-22 13:14 UTC, pasqualito79 commented
OK, could it be that the variable has another name than client_secret? Because I can't find anything similar to this...maybe ccsp-application-id? or ccsp-device-id? In the payload I also find things like did, pid, sid or uid.

2025-10-22 13:23 UTC, pasqualito79 commented
There is a POSt to /token with a form which contains client_id, code, grant_type and redirect_uri. In the response I get access_token, token_type and refresh_token back. The code value could be interesting, but it's all uppercase letters and numbers...

2025-10-22 13:25 UTC, martinpelant commented
Can you share the redirect uri?

2025-10-22 13:25 UTC, RustyDust commented
> OK, could it be that the variable has another name than client_secret?
Unlikely, if the backend code is the same as the one used by Kia/Hyundai.
Look for a POST request to "https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/token". This should have a payload of
- `grant_type`
- `code`
- `redirect_uri`
- `client_id`
- `client_secret`

where 
- `grant_type` is "authorization_code" (literal)
- `code` is returned by a previous call to "https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/authorize?..." (the whole URL with parameters would be of interest, too)
- `redirect_uri` is something like "https://prd.eu-ccapi.genesis.com...." (complete string would be of interest)
- `client_id` is the application's ID
- `client_secret` is the applications secret

2025-10-22 13:27 UTC, RustyDust commented
> There is a POSt to /token with a form which contains client_id, code, grant_type and redirect_uri. 

That's most likely the one we're looking for. It would be nice if you could post the whole thing (there really shouldn't be any personal data in there), just make sure to edit any username / password entries should those be present.

2025-10-22 13:51 UTC, pasqualito79 commented
so this is everything that is sent in the body of this request:

client_id=3020afa2-30ff-412a-aa51-d28fbe901e10&code=MDE2OWM4ODGTNWFMZS0ZZJU1LWJKYTMTNZGWNGQ0Y2QZNGZM&grant_type=authorization_code&redirect_uri=https%3A//accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2

2025-10-22 14:02 UTC, RustyDust commented
> so this is everything that is sent in the body of this request:

Thanks, unfortunately when I try this URL I get an error saying "client_id and client_secret is required for token request." :-( So we're still missing the `client_secret`. :-(
**However, when using the string "secret" (as Kia does) as the value for the additional payload "client secret", it seems to work.**
@martinpelant Can you try this using your credentials? I unfortunately don't have Genesis credentials to work with.

2025-10-22 14:04 UTC, martinpelant commented
getting:
```
➜  GitHub python3 genesis_part2.py

❌ Error getting tokens from der API!
{"retId":"3ee53324-a2a3-4d36-9a1a-eb5391df7865","retCode":4000,"retMsg":"Bad Request","retSubMsg":"\"clientSecret is wrong. requested clientId=3020afa2-30ff-412a-aa51-d28fbe901e10 requested clientSecret=secret\"","retValue":null}
```

2025-10-22 14:15 UTC, martinpelant commented
also appears that redirect uri is different for different client id

2025-10-22 14:21 UTC, martinpelant commented
trying this btw
```
        data = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": "https://accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2",
            "client_id": "3020afa2-30ff-412a-aa51-d28fbe901e10",
            "client_secret": "secret",
        }
        response = session.post(
            "https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/token", data=data
        )
``` 

with updated url for the code to use the same redirect url & client id: https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/authorize?client_id=50e3b8b0-ced5-43b7-8a42-f86ac92fe50e&scope=account.token.transfer%20account.id.generate%20account.puid.userinfos%20account.userinfo%20read%20account.userinfos%20puid%20email%20name%20mobileNum%20birthdate%20lang%20country%20signUpDate%20gender%20nationInfo%20certProfile%20offline&response_type=code&redirect_uri=https%3A//accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2&ui_locales=en-GB

2025-10-22 14:24 UTC, pasqualito79 commented
at the moment, Genesis has two completely different iOS apps which both work fine. I'll try the "old" one later again, maybe there's a secret somewhere...

2025-10-22 14:33 UTC, RustyDust commented
Just for completeness, here's my try using Postman. Note that since I don't have Genesis credentials I have no way to generate a working `code` entry. But the response was what let me to believe the `client_secret` "secret" might actually work. Seems like the test for a valid code comes before the test for a valid `client_secret` ;)

<img width="992" height="558" alt="Bildschirmfoto 2025-10-22 um 16 31 25" src="https://github.com/user-attachments/assets/f82e6037-7629-4e08-8166-132a426f8e0a" />

2025-10-22 14:35 UTC, RustyDust commented
> I'll try the "old" one later again, maybe there's a secret somewhere...

When doing so, please keep in mind that the older app quite likely also has a different client_id. So if you find a secret (keeping my fingers crossed) please also provide the client_id used with it.

2025-10-22 14:39 UTC, martinpelant commented
> Just for completeness, here's my try using Postman. Note that since I don't have Genesis credentials I have no way to generate a working `code` entry. But the response was what let me to believe the `client_secret` "secret" might actually work. Seems like the test for a valid code comes before the test for a valid `client_secret` ;)
> 
> <img alt="Bildschirmfoto 2025-10-22 um 16 31 25" width="992" height="558" src="https://private-user-images.githubusercontent.com/1085162/504238983-f82e6037-7629-4e08-8166-132a426f8e0a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExNDQyNTcsIm5iZiI6MTc2MTE0Mzk1NywicGF0aCI6Ii8xMDg1MTYyLzUwNDIzODk4My1mODJlNjAzNy03NjI5LTRlMDgtODE2Ni0xMzJhNDI2ZjhlMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMjJUMTQzOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U4ODgzMWM3NTYyMmFiMDZjM2NiOTg2YWUxMDE0ZjY2NmMwYzcxZDc4Zjk0ZmE2ZmFiZTYwOTNlZmNhMGZiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dJ_EjB99CnJcYVIOKn-RGm4u989UuuP_s-8LKis5RWQ">

Nope, secret test comes after (1st try with wrong code, 2nd try with right code):
```
➜  GitHub python3 genesis_part2.py

❌ Error getting tokens from der API!
{"retId":"72fefa46-a7f0-456a-a830-8fc946435994","retCode":4000,"retMsg":"Bad Request","retSubMsg":"\"code : justtest is not exist in redis\"","retValue":null}
Cleaning up and closing the browser.
➜  GitHub python3 genesis_part2.py

❌ Error getting tokens from der API!
{"retId":"9b188831-5e19-4ce6-97f5-703a99e7460a","retCode":4000,"retMsg":"Bad Request","retSubMsg":"\"clientSecret is wrong. requested clientId=3020afa2-30ff-412a-aa51-d28fbe901e10 requested clientSecret=secret\"","retValue":null}
Cleaning up and closing the browser.
➜  GitHub
```

2025-10-22 14:46 UTC, RustyDust commented
> Nope, secret test comes after (1st try with wrong code, 2nd try with right code):

Which is exactly what I said, just in reverse logic ;)

2025-10-22 14:49 UTC, martinpelant commented
if anyone knows how to get obfuscated strings from android app (they're using xshield ) it'll be here as well: https://gist.github.com/martinpelant/e38a6c32251f7e495baf998f3eb61fe3#file-gistfile1-txt-L81

2025-10-22 17:05 UTC, pasqualito79 commented
with the old app, I just get another code: 
client_id=3020afa2-30ff-412a-aa51-d28fbe901e10&code=YZNIZMQYNTATYMFJOC0ZYJC3LTLHNJQTZJK2OTC3M2EXZWRJ&grant_type=authorization_code&redirect_uri=https%3A//accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2

2025-10-22 17:11 UTC, pasqualito79 commented
What I don't really understand is how can the python code  (https://github.com/RobXYZ/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/KiaUvoApiEU.py) work  - so I can login and get data? There's no "secret" there in the whole code...

2025-10-22 17:53 UTC, RustyDust commented
> What I don't really understand is how can the python code work 

That's because you're looking at old code that doesn't work anymore anyway. Which is the reason for the hunt after the `client_secret` that is needed to fetch the refresh token. In the version of the Python code you linked to, the software tried to emulate the login process and retrieve the refresh token by itself. This method has been blocked by Hyundai/Kia/Genesis by using a Captcha in the login process. So since the code now can no longer get the refresh token users need an alternative method to get it and provide it to the new routines which  also don't need the `client_secret` because that's only needed to get the `refresh_token` but not anymore afterwards.

2025-10-22 17:55 UTC, martinpelant commented
slight offtopic - do we know how long is the refresh token valid?

2025-10-22 17:56 UTC, RustyDust commented
> slight offtopic - do we know how long is the refresh token valid?

The API documentation says 180 days.

2025-10-22 18:02 UTC, martinpelant commented
> with the old app, I just get another code:
client_id=3020afa2-30ff-412a-aa51-d28fbe901e10&code=YZNIZMQYNTATYMFJOC0ZYJC3LTLHNJQTZJK2OTC3M2EXZWRJ&grant_type=authorization_code&redirect_uri=https%3A//accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2

anything in headers or elsewhere in post data? Or maybe in a request before? Your code looks to have different format than mine.

2025-10-22 18:36 UTC, martinpelant commented
btw if you have mac each time you run selenium script it'll make a copy of chrome app that doesn't get cleaned up https://www.reddit.com/r/MacOS/comments/1hxxpg7/found_a_google_chrome_clone_on_my_mac/
I just deleted 120GB worth of try runs of my script :D

2025-10-22 19:04 UTC, pasqualito79 commented
> > What I don't really understand is how can the python code work
> 
> That's because you're looking at old code that doesn't work anymore anyway. Which is the reason for the hunt after the `client_secret` that is needed to fetch the refresh token. In the version of the Python code you linked to, the software tried to emulate the login process and retrieve the refresh token by itself. This method has been blocked by Hyundai/Kia/Genesis by using a Captcha in the login process. So since the code now can no longer get the refresh token users need an alternative method to get it and provide it to the new routines which also don't need the `client_secret` because that's only needed to get the `refresh_token` but not anymore afterwards.

thanks for the explanation!

2025-10-22 19:05 UTC, pasqualito79 commented
> slight offtopic - do we know how long is the refresh token valid?

I found this in the response where I get the token:

"expires_in": 3600

2025-10-22 19:12 UTC, pasqualito79 commented
OK here are the first few requests until I get the token:

<img width="1438" height="294" alt="image" src="https://github.com/user-attachments/assets/6fe5f1b8-2c07-474a-965d-63df887d8555" />

<img width="1447" height="489" alt="image" src="https://github.com/user-attachments/assets/11f314c0-b4b8-4340-8d3e-17572b808f3a" />

<img width="1444" height="354" alt="image" src="https://github.com/user-attachments/assets/6f02f525-c1f1-462e-b68d-f38845f07389" />

<img width="1448" height="392" alt="image" src="https://github.com/user-attachments/assets/6dd7ce25-fcde-443b-9deb-781edc522889" />

<img width="1443" height="464" alt="image" src="https://github.com/user-attachments/assets/5320f2da-c99e-48bb-bbee-baee1a08b7db" />

2025-10-22 19:13 UTC, RustyDust commented
> I found this in the response where I get the token: "expires_in": 3600

Yup, but that's the expiry for the `access_token`. The long lived `refresh_token` is used to generate a short lived access token.

2025-10-22 19:28 UTC, pasqualito79 commented
maybe this query in the first request could also be interesting:
<img width="1445" height="371" alt="image" src="https://github.com/user-attachments/assets/492fbc78-9398-4bc2-b707-a276e2266043" />

2025-10-22 19:38 UTC, martinpelant commented
hmm this flow looks very different to kia/hyundai

2025-10-22 19:41 UTC, pasqualito79 commented
that's done with the "old" app...but is exactly the same as my post on 3.8. where you can see the complete flow

2025-10-22 19:52 UTC, pasqualito79 commented
When using proxyman with the new app, login still works but afterwards it says that the service is restricted because of an unstable connection to the vehicle. Only possible to lock or unlock doors in this mode. The new app is the one that also uses captchas for the login, the old one doesn't have this feature. So my guess is, that because Genesis has two apps with different message flows, as long as the old app works, the old python code still works for Genesis only. But just a matter of time when they will shut it off...

2025-10-22 20:28 UTC, RustyDust commented
> When using proxyman with the new app, login still works but afterwards it says that the service is restricted because of an unstable connection to the vehicle.

This is not a problem as long as you get a refresh_token. This part would be the interesting one. Everything else is not really important for the Python module.

2025-10-22 20:44 UTC, pasqualito79 commented
With the new app, I get more than one token in the response. This is how it looks: 
<img width="1446" height="907" alt="image" src="https://github.com/user-attachments/assets/8daebd50-929b-463a-b430-74a6fc7a687f" />

anything more that could be interesting in this request?

2025-10-22 20:58 UTC, martinpelant commented
And does the request body by any chance include the secret?

2025-10-22 21:01 UTC, pasqualito79 commented
it seems not...
<img width="368" height="577" alt="image" src="https://github.com/user-attachments/assets/40b815c0-6dd0-4458-aa44-2a5d9d1d4ac3" />

2025-10-22 21:03 UTC, martinpelant commented
That looks like response or is it a request?

2025-10-22 21:08 UTC, RustyDust commented
> With the new app, I get more than one token in the response. This is how it looks:

I think this is the request 1 step _before_ the one we're interested in. The "code" in the request URL is later on used to generate the real `request_token`.

2025-10-22 21:09 UTC, pasqualito79 commented
> That looks like response or is it a request?

that's the response body, just as a tree view

2025-10-22 21:11 UTC, martinpelant commented
Can you share what's in the request body? (Of course strip any login info of present)

2025-10-22 21:17 UTC, pasqualito79 commented
> Can you share what's in the request body? (Of course strip any login info of present)

request body is completely empty

2025-10-22 21:19 UTC, pasqualito79 commented
here are the requests before getting the token:

<img width="1663" height="600" alt="image" src="https://github.com/user-attachments/assets/a6713b26-b9dc-42a7-be73-a951c54b161c" />
<img width="1672" height="441" alt="image" src="https://github.com/user-attachments/assets/52da042c-61da-4d26-9b39-729e63212b1b" />
<img width="1668" height="449" alt="image" src="https://github.com/user-attachments/assets/ef8b475b-fdc8-4b74-99dc-6d9a4b6baa11" />
<img width="1656" height="519" alt="image" src="https://github.com/user-attachments/assets/0e0f5636-6660-4533-89f3-68f0edc2331e" />

2025-11-13 13:33 UTC, martinpelant commented
Found working client id & secret from old decompiling GCS app:

```
        data = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": "https://accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2",
            "client_id": "3020afa2-30ff-412a-aa51-d28fbe901e10",
            "client_secret": "FKDdlef2ffdleFEweELFKERiLER2FED21sDdwdgQz6hFESE3",
        }
       response = session.post(
            "https://idpconnect-eu.genesis.com/auth/api/v2/user/oauth2/token", data=data
        )
        if response.status_code == 200:
            tokens = response.json()
            if tokens is not None:
                refresh_token = tokens["refresh_token"]
                access_token = tokens["access_token"]
                print(
                    f"\n✅ Your tokens are:\n\n- Refresh Token: {refresh_token}\n- Access Token: {access_token}"
                )
```

2025-11-13 14:21 UTC, martinpelant commented
Unfortunately latest matser of the kia_connect_api doesn't work out of the box

```
➜  hyundai_kia_connect_api git:(master) ✗ python3 testGenesis.py
2025-11-13 13:49:56,128 - hyundai_kia_connect_api.KiaUvoApiEU - DEBUG - hyundai_kia_connect_api - Get Device ID request: https://prd-eu-ccapi.genesis.com:443/api/v1/spa/notifications/register {'ccsp-service-id': '3020afa2-30ff-412a-aa51-d28fbe901e10', 'ccsp-application-id': 'f11f2b86-e0e7-4851-90df-5600b01d8b70', 'Stamp': 'ImpZIJ2NNURLI0cNUotk8b8G05h70TJzbvXLirZ/QKkhptv+KoiKr99fihFTx5w=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd-eu-ccapi.genesis.com:443', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': '541fd7e13755628295a84112e602be4d2d8f4f96a6e75330cb2a5e4c7442506e', 'pushType': 'GCM', 'uuid': '4e62ace2-2eae-4e10-a4f2-f8796497fcb3'}
2025-11-13 13:49:56,411 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): prd-eu-ccapi.genesis.com:443
2025-11-13 13:49:56,632 - urllib3.connectionpool - DEBUG - https://prd-eu-ccapi.genesis.com:443 "POST /api/v1/spa/notifications/register HTTP/1.1" 200 140
2025-11-13 13:49:56,633 - hyundai_kia_connect_api.KiaUvoApiEU - DEBUG - hyundai_kia_connect_api - Get Device ID response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'deviceId': 'a0c82b11-839d-4e18-911a-3cdcb52e8418'}, 'msgId': 'a38ff280-c097-11f0-a3c2-50df1a3f02fa'}
2025-11-13 13:49:56,634 - hyundai_kia_connect_api.KiaUvoApiEU - DEBUG - hyundai_kia_connect_api - Get cookies request: https://prd-eu-ccapi.genesis.com:443/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=3020afa2-30ff-412a-aa51-d28fbe901e10&redirect_uri=https://prd-eu-ccapi.genesis.com:443/api/v1/user/oauth2/redirect&lang=en
2025-11-13 13:49:56,637 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): prd-eu-ccapi.genesis.com:443
2025-11-13 13:49:56,749 - urllib3.connectionpool - DEBUG - https://prd-eu-ccapi.genesis.com:443 "GET /api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=3020afa2-30ff-412a-aa51-d28fbe901e10&redirect_uri=https://prd-eu-ccapi.genesis.com:443/api/v1/user/oauth2/redirect&lang=en HTTP/1.1" 400 96
2025-11-13 13:49:56,751 - hyundai_kia_connect_api.KiaUvoApiEU - DEBUG - hyundai_kia_connect_api - Get cookies response: {'account': '<redacted>'}
2025-11-13 13:49:56,755 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): prd-eu-ccapi.genesis.com:443
2025-11-13 13:49:56,852 - urllib3.connectionpool - DEBUG - https://prd-eu-ccapi.genesis.com:443 "POST /api/v1/user/language HTTP/1.1" 401 100
2025-11-13 13:49:56,871 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): idpconnect-eu.genesis.com:443
2025-11-13 13:49:57,025 - urllib3.connectionpool - DEBUG - https://idpconnect-eu.genesis.com:443 "POST /auth/api/v2/user/oauth2/token HTTP/1.1" 400 260
2025-11-13 13:49:57,026 - hyundai_kia_connect_api.KiaUvoApiEU - DEBUG - hyundai_kia_connect_api - Get Access Token Response: {'retId': 'f3077db4-7060-43e9-b0af-6289d0ffb901', 'retCode': 7501, 'retMsg': 'Received unexpected statusCode', 'retSubMsg': '{"errId":"44a3e2c4-0b6a-477b-8f26-f95e6b76f18f","errCode":"4002","errMsg":"Invalid parameters","errBody":null}', 'retValue': None}
Traceback (most recent call last):
  File "/Users/pelant/GitHub/hyundai_kia_connect_api/testGenesis.py", line 10, in <module>
    vm.check_and_refresh_token()
  File "/Users/pelant/GitHub/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 153, in check_and_refresh_token
    self.initialize()
  File "/Users/pelant/GitHub/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 84, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pelant/GitHub/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 192, in login
    _, access_token, authorization_code, expires_in = self._get_access_token(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pelant/GitHub/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1326, in _get_access_token
    _check_response_for_errors(response)
  File "/Users/pelant/GitHub/hyundai_kia_connect_api/hyundai_kia_connect_api/ApiImplType1.py", line 111, in _check_response_for_errors
    raise AuthenticationError(retMSG)
hyundai_kia_connect_api.exceptions.AuthenticationError: Received unexpected statusCode
```

2025-11-14 10:14 UTC, RustyDust commented
@martinpelant 
> 2025-11-13 13:49:57,026 - hyundai_kia_connect_api.KiaUvoApiEU - DEBUG - hyundai_kia_connect_api - Get Access Token Response: {'retId': 'f3077db4-7060-43e9-b0af-6289d0ffb901', 'retCode': 7501, 'retMsg': 'Received unexpected statusCode', 'retSubMsg': '{"errId":"44a3e2c4-0b6a-477b-8f26-f95e6b76f18f","errCode":"4002","errMsg":"Invalid parameters","errBody":null}', 'retValue': None}

That's where the problem is. Looks like the Genesis API expect some more or other parameters than the one you're sending (see last part of message).

2025-11-15 13:00 UTC, pasqualito79 commented
Can we find the correct parameters in the requests from the app?

2025-11-15 13:29 UTC, RustyDust commented
> Can we find the correct parameters in the requests from the app?

That's quite likely, however, since I don't own a Genesis I don't own the app nor do I have working credentials. But if you're able to trace the calls from the App it is more than likely that it will make a request to `/auth/api/v2/user/oauth2/token` endpoint with the needed parameters.

2025-11-15 13:51 UTC, pasqualito79 commented
The problem is, that the new Genesis app (with v2 tokens) is blocking everything when trying to capture the https traffic. I posted the screenshot of the v1 token request with the old app above because this app doesn't block SSL proxying....but I guess that doesn't help :-(

2025-11-17 21:52 UTC, pasqualito79 commented
With Frida it may be possible to get around this SSL pinning issue: https://blog.kumo.dev/2024/05/22/reverse_engineering_hkg_apps.html
sounds like a bigger project, especially on iOS with jailbreaking...

But now I found this post in the discord group of Bluelink:

<img width="980" height="110" alt="image" src="https://github.com/user-attachments/assets/88d68c57-03f8-4097-a7df-1c9de62ac2da" />

so there may be a solution coming soon...I wrote this guy, hope he'll answer soon

2025-11-25 21:00 UTC, pasqualito79 commented
Well, he only got v1 tokens...but this still works, so why not use them as long as the old app is not deprecated?
When I use proxyman on the old app, those are the parameters:
client_id=3020afa2-30ff-412a-aa51-d28fbe901e10&code=XXX&grant_type=authorization_code&redirect_uri=https%3A//accounts-eu.genesis.com/realms/eugenesisidm/ga-api/redirect2

2025-11-30 13:04 UTC, martinpelant commented
The decompiled apk has this however it doesn't work when I provide the params in the script (was out for 2 weeks and only got back now. Can try playing with it more later)
<img width="1697" height="292" alt="Screenshot 2025-11-30 at 1 02 43 PM" src="https://github.com/user-attachments/assets/480f2e7f-b95c-4f69-99e7-bbb701d7cf7f" />

2025-11-30 13:11 UTC, martinpelant commented
and values are these
<img width="2182" height="407" alt="Screenshot 2025-11-30 at 1 09 49 PM" src="https://github.com/user-attachments/assets/624bdd62-02b8-4a9a-bf5b-d64c5a689d64" />
so exactly like the KiaUvoApiEu (with updated client ID & secret) has but still returns wrong param

2026-01-17 05:40 UTC, cdnninja commented
Closing please open as new PRs if interested in genesis changes.

2026-01-17 05:40 UTC, closed without merging

2026-03-02 21:33 UTC, martinpelant commented
Finally managed to workaround ssl pining and capture whole login flow and here's a working python script go get access tokens https://gist.github.com/martinpelant/bdb3017985ae6206939af53aff955d6a

2026-03-03 23:43 UTC, martinpelant commented
managed to fetch list of vehicles but the details are missing - see https://github.com/martinpelant/hyundai_kia_connect_api_genesis/commit/b3a9510c262ebafd90857ad93395ed371d2ebbb3 . The API for vehicle detail is also different and can't grab it because app detects different certificate and restricts usage: 
<img width="1080" height="2400" alt="Screenshot_1772581366" src="https://github.com/user-attachments/assets/45abdb8f-d3de-4fa5-8c45-d9c076389c02" />

2026-03-17 19:40 UTC, martinpelant commented
Got it working in HA! For now just in my fork: https://github.com/martinpelant/hyundai_kia_connect_api_genesis
Will monitor for a while

2026-03-31 07:28 UTC, wkram commented
Hi Martin.

This sounds great. I just tried and succeeded in getting a "GENESIS ENCODED TOKEN STRING":

[*] Exchanging code for tokens...
[+] SUCCESS! Tokens retrieved.
[+] Excellent! You received a 90.0-day token. It should not expire overnight.

How do I use it in HA? By using the official "Kia Uvo / Hyundai Bluelink" HACS integration? My Login within this integration doesn't work for my Genesis GV70. Hope you have an idea.

Regards
Flo

2026-03-31 08:53 UTC, martinpelant commented
Just replace requirements in your custem_components/kia_uvo/manifest.json 
with this:
`  "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@565831d#hyundai_kia_connect_api==1.0.4"],` and restart HA. For me all the sensors had been updating correctly on my GV60 since this last commit but some write APIs still fail (like setting charge level) though I don't use it to control the car so don't plan on spending any more time on this in the near future. I mainly want to track my odometer & battery level

2026-03-31 14:04 UTC, AndreasLat commented
> Just replace requirements in your custem_components/kia_uvo/manifest.json with this: ` "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@565831d#hyundai_kia_connect_api==1.0.4"],` and restart HA. For me all the sensors had been updating correctly on my GV60 since this last commit but some write APIs still fail (like setting charge level) though I don't use it to control the car so don't plan on spending any more time on this in the near future. I mainly want to track my odometer & battery level

I replaced the "requirements" line in my file and restarted HA but it still does not work. Should this work for Genesis in Europe?

2026-03-31 14:09 UTC, martinpelant commented
yes it does work for me for GV60 in the UK. Did you select Genesis, Europe from the dropdown and pasted the super long G: encoded tokens string into password field (generated with this script: https://github.com/martinpelant/hyundai_kia_connect_api_genesis/blob/master/genesis_login.py )? Also not sure (as I haven't tried with a wrong one) but did you enter correct pin  that you use in the app?

2026-03-31 14:10 UTC, martinpelant commented
also for what it's worth I'm on v2.51.1 of the integration

```
{
  "domain": "kia_uvo",
  "name": "Kia Uvo / Hyundai Bluelink",
  "codeowners": ["@fuatakgun"],
  "config_flow": true,
  "documentation": "https://github.com/Hyundai-Kia-Connect/kia_uvo",
  "integration_type": "hub",
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/Hyundai-Kia-Connect/kia_uvo/issues",
  "loggers": ["kia_uvo", "hyundai_kia_connect_api"],
  "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@565831d#hyundai_kia_connect_api==1.0.4"],
  "version": "2.51.1"
}
```

2026-03-31 14:13 UTC, AndreasLat commented
> "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@565831d#hyundai_kia_connect_api==1.0.4"],

Thank you for your fast reply. I copied the following: "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@565831d#hyundai_kia_connect_api==1.0.4"], into my json file. I do not know what you mean with the super long G: encoded tokens string for the passowrd. I only choose the password from my genesis account. On top I do not have a Pin defined. How do I have to define it?

2026-03-31 14:14 UTC, martinpelant commented
> > "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@[565831d](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/565831d8bcbd659b2bae375e7ef3f45884112fbe)#hyundai_kia_connect_api==1.0.4"],
> 
> Thank you for your fast reply. I copied the following: "requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@[565831d](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/565831d8bcbd659b2bae375e7ef3f45884112fbe)#hyundai_kia_connect_api==1.0.4"], into my json file. I do not know what you mean with the super long G: encoded tokens string for the passowrd. I only choose the password from my genesis account. On top I do not have a Pin defined. How do I have to define it?

I've updated my previous commet - see https://github.com/martinpelant/hyundai_kia_connect_api_genesis/blob/master/genesis_login.py  you need to use this to generate the G: string that will be used as a password in the integration

2026-03-31 14:20 UTC, AndreasLat commented
Sorry, I am not an IT Specialist and do not know what I have to do with this phyton script you sent the link to. No problem if you say, that this can only be used by specialists, I just allowed me to ask for a recipe

2026-03-31 14:32 UTC, martinpelant commented
you need to run `python3 genesis_login.py` from your terminal and follow the instructions. Alternatively I've created an android companion app that does it on your phone - you just log in and it'll generate the string for you. Generally I'd advise against installing any binary from unverified source but I'm just adding it here including source and it's up to you what you decide to do with it and if you trust it...) 
[genesis_android_companion.zip](https://github.com/user-attachments/files/26381072/genesis_android_companion.zip)

2026-03-31 14:56 UTC, AndreasLat commented
Wow, perfect, It worked properly, thank you very much!!!

2026-03-31 15:12 UTC, wkram commented
Hi.

I tested your solution. I am one step further. Login seems to work, but I get the following error:

KeyError: 15 in KiaUvoApiEU.py, Zeile 619:                                                                                                                                                                                                        
                                                                                                                                                                                                                                                  
  vehicle.rear_left_seat_status = SEAT_STATUS[                                                                                                                                                                                                      
      get_child_value(state, "vehicleStatus.seatHeaterVentState.rlSeatHeatState")                                                                                                                                                                   
  ]                                                                                                                                                                                                                                                 
  KeyError: 15                                                                                                                                                                                                                                      

The problem: The Genesis API returns the value 15 for the seat heater status (rlSeatHeatState), but the SEAT_STATUS dictionary in const.py only defines values from 0-8. The value 15 (0b1111) is not defined, causing a KeyError. I don't know what this status (15) means.

Possible fix:
  1. const.py: Add 15: "Unknown" to the SEAT_STATUS dictionary
  2. KiaUvoApiEU.py: Replace all SEAT_STATUS[...] with SEAT_STATUS.get(...) so that unknown values no longer cause a crash

Regards
Flo

2026-03-31 15:15 UTC, martinpelant commented
Interesting, I've had this error in the past before they changed the API and happened very sporadically for me (almost like if there was some server side ab test on which value it returns). Haven't had this issue since I got it working again this month.

2026-04-02 09:43 UTC, AndreasLat commented
It worked two days. Now not anymore. I get the following error message:
Einrichtungsfehler, wird erneut versucht: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 149, in _async_update_data await self.hass.async_add_executor_job( ...<2 lines>... ) File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run result = ctx.run(self.task) File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run return fn(*args, **kwargs) File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 156, in check_and_force_update_vehicles self.check_and_force_update_vehicle(force_refresh_interval, vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 176, in check_and_force_update_vehicle self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 142, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 508, in update_vehicle_with_cached_state self._update_vehicle_properties( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ vehicle, response["resMsg"]["vehicleStatusInfo"] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 619, in _update_vehicle_properties vehicle.rear_left_seat_status = SEAT_STATUS[ ~~~~~~~~~~~^ get_child_value(state, "vehicleStatus.seatHeaterVentState.rlSeatHeatState") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ] ^ KeyError: 15 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 158, in _async_update_data await self.hass.async_add_executor_job( self.vehicle_manager.update_all_vehicles_with_cached_state ) File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run result = ctx.run(self.task) File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run return fn(*args, **kwargs) File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 137, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 142, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 508, in update_vehicle_with_cached_state self._update_vehicle_properties( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ vehicle, response["resMsg"]["vehicleStatusInfo"] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.14/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 619, in _update_vehicle_properties vehicle.rear_left_seat_status = SEAT_STATUS[ ~~~~~~~~~~~^ get_child_value(state, "vehicleStatus.seatHeaterVentState.rlSeatHeatState") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ] ^ KeyError: 1

2026-04-02 09:50 UTC, martinpelant commented
yeah that's the HeatState issue that @wkram mentioned. I haven't hit it myself yet  but previously I just skipped the seat heating values altogether: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/3f67c9eb0ab50c6c2185d0a536a47028ce27e944

2026-04-02 10:14 UTC, martinpelant commented
try updating the dependency to 
`"requirements": ["git+https://github.com/martinpelant/hyundai_kia_connect_api_genesis.git@a9859a2"]` 
(I've skipped the seats on this branch too https://github.com/martinpelant/hyundai_kia_connect_api_genesis/commit/a9859a27e815f506fbe4f158f21b09e2495ba2b5)

2026-04-22 12:04 UTC, AndreasLat commented
Unfortunatelly the python3 genesis_login.py does not work anymore as described. 
The page is unavailable because your authentication has expired.
The page is no longer available due to expired credentials,
or this is not a valid request.
<img width="605" height="468" alt="Screenshot 2026-04-22 140336" src="https://github.com/user-attachments/assets/856315a4-c7fc-4c13-98b6-c9e01ea643dd" />