fix: handle EU server time issue
Hyundai-Kia-Connect/hyundai_kia_connect_api pull request #642
Opened 2024-10-04 19:59 UTC by cdnninja

Sometimes EU reports old time stamps

2024-10-04 20:00 UTC, cdnninja commented
@ZuinigeRijder  you are thinking move this logic to the vehicle setting?

2024-10-04 20:02 UTC, ZuinigeRijder commented
Yes, I can make a proposal (new) Pull request?

2024-10-04 20:03 UTC, cdnninja commented
Of course! This is as much yours as mine! I don't have one of these cars anymore so can't say I spend much time on it.  I just increased your access to admin on this repo as well.

2024-10-04 20:51 UTC, ZuinigeRijder commented on hyundai_kia_connect_api/ApiImplType1.py
>                      get_child_value(state, "Date"), dt.timezone.utc
I think this was wrong, someone else already reported that this was wrong for ccs2, it should be self.data_timezone

2024-10-05 05:59 UTC, ZuinigeRijder requested changes

2024-10-05 06:06 UTC, closed without merging